### ISSUE TITLE
Cucumber 6.0.1  doesn't work with cucumber-pretty 1.5.2 and lower

### ISSUE THREAD

**Issue by Znakki** [kozhevnikov/cucumber-pretty#10]
The other day, cucumberjs released a new vesion
The latest version is 6.0.1.

_Precondition:_ 
install latest package versions  namely,
   "cucumber": "**6.0.1**",
    "cucumber-pretty": "**1.5.2**",

**Steps to reproduce:** 
run the cucumber: 
./node_modules/.bin/cucumber-js  --format node_modules/cucumber-pretty

**Actual result:**
 { TypeError: **options.eventDataCollector.getTestCaseData is not a function**
    at EventEmitter.PrettyFormatter.options.eventBroadcaster.on (/Users/userName/Projects/projectName-testing/node_modules/cucumber-pretty/index.js:52:70)
    at EventEmitter.emit (events.js:187:15)
    at EventEmitter.emit (domain.js:442:20)

**Comment by kozhevnikov** [comment]
Fixed in cucumber-pretty@^6.0.0

**Comment by Roomysy** [comment]
Hi All
I'm still getting this error

"protractor": "^7.0.0",
"cucumber": "^6.0.5",
"cucumber-pretty": "^6.0.0"

TypeError: formatter.eventDataCollector.getTestCaseData is not a function at logTestCaseStarted (C:\Users\username\AppData\Roaming\JetBrains\IntelliJIdea2020.1\plugins\CucumberJavaScript\lib\cucumberjs_formatter_v3.js:89:47)
    at EventEmitter.emit (events.js:327:22)

**Comment by kozhevnikov** [comment]
@CoronaQa based on the location of the error it seems to be a bug in IntelliJ's Cucumber.js plugin. Can you run it from command line without the IntelliJ?

**Comment by Roomysy** [comment]
It works now.
Thanks
